--	----	----	----		Modern Mobs 	----	----	----	--

--	----	Team D - Police	----	--

--	Officer
mobs:register_mob("mobs_modern:moTDAof", {
	type = "armyd", "td", "npc",
	hp_min = 13,
	hp_max = 25,
	collisionbox = {-0.3, -0.8, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.b3d",
	textures = {
		{"TD_vil_pol1.png",		"3d_armor_trans.png",	minetest.registered_items["mobs_modern:weapon_g36"].inventory_image,},
		{"TD_vil_pol2.png",		"3d_armor_trans.png",	minetest.registered_items["mobs_modern:weapon_g36"].inventory_image,},
		{"TD_vil_pol3.png",		"3d_armor_trans.png",	minetest.registered_items["mobs_modern:weapon_m200"].inventory_image,},
		{"TD_vil_pol4.png",		"3d_armor_trans.png",	minetest.registered_items["mobs_modern:weapon_g36"].inventory_image,},
		{"TD_vil_pol5.png",		"3d_armor_trans.png",	minetest.registered_items["mobs_modern:weapon_g36"].inventory_image,},
--		{"TD_vil_pol6.png",		"3d_armor_trans.png",	minetest.registered_items["mobs_modern:weapon_g36"].inventory_image,},
	},
	visual_size = {x=1, y=.8},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 1.5,
	run_velocity = 3,
	damage = 2.5,
	drops = {
		{name = "default:leaves",
		chance = 1,
		min = 3,
		max = 5,},
		{name = "default:sword_steel",
		chance = 2,
		min = 0,
		max = 1,},
	},
	armor = 95,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	fear_height = 5,
	attack_type = "dogshoot",
	dogshoot_switch = 1,
	dogshoot_count_max = 4.8, -- shoot for 4 seconds
	dogshoot_count2_max = 2.4, -- dogfight for 2 seconds
	reach = 2,
	punch_interval = 1.5,
	shoot_interval = 1.2,
	arrow = "mobs_modern:bullet",
	shoot_offset = 2,
	pathfinding = true,
	animation = {
		speed_normal = 15,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_oerkki_attack",
		death = "mobs_death1",
		attack = "default_punch",
		},

	attacks_monsters = true,
	attacks_animals = true,
	attacks_tabs = true,
	attacks_tacs = true,
	peaceful = true,
	group_attack = true,
})

--	Special Unit
mobs:register_mob("mobs_modern:moTDAsp", {
	type = "armyd", "td", "npc",
	hp_min = 29,
	hp_max = 43,
	collisionbox = {-0.3, -0.6, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.b3d",
	textures = {
		{"TA_vil_cit1.png",		"3d_armor_trans.png",	minetest.registered_items["mobs_modern:weapon_g36"].inventory_image,},
   		{"TA_vil_cit2.png",		"3d_armor_trans.png",	minetest.registered_items["mobs_modern:weapon_g36"].inventory_image,},
		{"TA_vil_cit3.png",		"3d_armor_trans.png",	minetest.registered_items["mobs_modern:weapon_m200"].inventory_image,},
		{"TA_vil_cit4.png",		"3d_armor_trans.png",	minetest.registered_items["mobs_modern:weapon_g36"].inventory_image,},
--  	{"TA_vil_cit5.png",		"3d_armor_trans.png",	minetest.registered_items["mobs_modern:weapon_g36"].inventory_image,},
--		{"TA_vil_cit6.png",		"3d_armor_trans.png",	minetest.registered_items["mobs_modern:weapon_m200"].inventory_image,},
--		{"TA_vil_cit7.png",		"3d_armor_trans.png",	minetest.registered_items["mobs_modern:weapon_g36"].inventory_image,},
--   	{"TA_vil_cit8.png",		"3d_armor_trans.png",	minetest.registered_items["mobs_modern:weapon_g36"].inventory_image,},
	},
	visual_size = {x=1.2, y=1},
	makes_footstep_sound = true,
	view_range = 14,
	walk_velocity = 0.1,
	run_velocity = 2,
	damage = 3,
	drops = {
		{name = "default:stone_with_mese",
		chance = 7,
		min = 0,
		max = 5,},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	on_rightclick = nil,
	attack_type = "dogshoot",
	dogshoot_switch = 1,
	dogshoot_count_max = 3, -- shoot for 4 seconds
	dogshoot_count2_max = 1, -- dogfight for 2 seconds
	reach = 2,
	punch_interval = 1,
	shoot_interval = .2,
	arrow = "mobs_modern:bullet",
	shoot_offset = 2,
	pathfinding = true,
	group_attack = true,
	replace_rate = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_offset = -1,
	peaceful = true,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell2",
		death = "mobs_howl",
		attack = "default_punch3",
		},
})

--	Agent
mobs:register_mob("mobs_modern:moTDAag", {
	type = "armyd", "td", "npc",
	hp_min = 29,
	hp_max = 43,
	collisionbox = {-0.3, -0.8, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.b3d",
	textures = {{"TA_vil_cri1.png",
			"3d_armor_trans.png",
				minetest.registered_items["default:sword_steel"].inventory_image,}
			},
	visual_size = {x=1, y=1},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 0.1,
	run_velocity = 2,
	damage = 4,
	drops = {
		{name = "default:stone_with_mese",
		chance = 7,
		min = 0,
		max = 5,},
		{name = "default:sword_steel",
		chance = 1,
		min = 0,
		max = 1,},
	},
	armor = 85,
	drawtype = "front",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	on_rightclick = nil,
	docile_by_day = true,
	attack_type = "dogshoot",
	dogshoot_switch = 1,
	dogshoot_count_max = 3, -- shoot for 4 seconds
	dogshoot_count2_max = 2, -- dogfight for 2 seconds
	reach = 2,
	punch_interval = 1.5,
	shoot_interval = .3,
	arrow = "mobs_modern:bullet",
	shoot_offset = 2,
	attack_npcs = true,
	attacks_tas = true,
	pathfinding = true,
	group_attack = true,
	replace_rate = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_offset = -1,
	peaceful = false,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell2",
		death = "mobs_howl",
		attack = "default_punch3",
		},
})


mobs:register_spawn("mobs_modern:moTDva", {"mobs_modern:ntdc"}, 5, 0, 10000, 1, 31000)

mobs:register_egg("mobs_modern:moTDAof", "Police Officer (moTD)", "default_leaves.png", 1)
--	mobs:register_egg("mobs_modern:moTDAsp", "SWAT Officer (moTD)", "default_leaves.png", 1)
--	mobs:register_egg("mobs_modern:moTDAag", "Agent (moTD)", "default_leaves.png", 1)